name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push
jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    steps:
      - run: terraform apply -auto-approve
        env:
          bucket_prefix: ${{secrets.BUCKET_PREFIX}}
          access_key: ${{secrets.ACCESS_KEY}}
          secret_key: ${{secrets.SECRET_KEY}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
