name: 'Terraform GitHub Actions'
on:
  - pull_request
  - push
jobs:
  terraform:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.18
          tf_actions_subcommand: "apply"
          variables: |
            bucket_prefix: "${{secrets.BUCKET_PREFIX}}"
            access_key: "${{secrets.ACCESS_KEY}}"
            secret_key: "${{secrets.SECRET_KEY}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}